// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

// This file stands in for the output of protoc-gen-go-grpc. The query finds
// a gRPC handler through the server interface that this file declares.

package handlers

import (
	"context"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// ThingServiceServer is the server API for ThingService.
type ThingServiceServer interface {
	GetThing(context.Context, *Request) (*Response, error)
	GetDeep(context.Context, *Request) (*Response, error)
	GetCoded(context.Context, *Request) (*Response, error)
	GetConnect(context.Context, *Request) (*Response, error)
	GetStatusErr(context.Context, *Request) (*Response, error)
	GetHelperCoded(context.Context, *Request) (*Response, error)
	GetSentinel(context.Context, *Request) (*Response, error)
	GetByScope(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedThingServiceServer()
}

// UnimplementedThingServiceServer must be embedded by each implementation.
type UnimplementedThingServiceServer struct{}

func (UnimplementedThingServiceServer) GetThing(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetThing not implemented")
}
func (UnimplementedThingServiceServer) GetDeep(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeep not implemented")
}
func (UnimplementedThingServiceServer) GetCoded(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCoded not implemented")
}
func (UnimplementedThingServiceServer) GetConnect(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConnect not implemented")
}
func (UnimplementedThingServiceServer) GetStatusErr(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatusErr not implemented")
}
func (UnimplementedThingServiceServer) GetHelperCoded(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHelperCoded not implemented")
}
func (UnimplementedThingServiceServer) GetSentinel(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSentinel not implemented")
}
func (UnimplementedThingServiceServer) GetByScope(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByScope not implemented")
}
func (UnimplementedThingServiceServer) mustEmbedUnimplementedThingServiceServer() {}

type invoker interface {
	Invoke(ctx context.Context, method string, in, out any) error
}

// thingServiceClient is the generated client. Its methods have the shape of
// a handler but are not one. Negative: the transport already set the code.
type thingServiceClient struct{ cc invoker }

func (c *thingServiceClient) GetThing(ctx context.Context, in *Request) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/thing.v1.ThingService/GetThing", in, out)
	if err != nil {
		return nil, err
	}
	return out, nil
}
